app/mod_admin/forms.py
from flask.ext.wtf import Form
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.fields import TextField, SubmitField, HiddenField, BooleanField
from wtforms.validators import Required

from app.performance_summary import s
from app.models import *


def users():
    return s.query(Users)

class UserForm(Form):
    name = TextField("Username",  [Required("Enter a Username")])
    admin = BooleanField("Admin")
    submit = SubmitField("Send")

app/mod_admin/views.py
from collections import OrderedDict

from app.queries import get_users, get_username_by_user_id
from queries import check_if_admin, get_user_id_by_username
from flask import Blueprint
from flask import render_template, request, url_for, redirect
from flask.ext.login import login_required, current_user

from app.performance_summary import s
from app.views import admin_required
from flask_table import Table, Col, LinkCol
from forms import UserForm
from queries import create_user, toggle_admin_query


class ItemTableUsers(Table):
    username = Col('User')
    admin = Col('Admin')
    toggle_admin = LinkCol('Toggle Admin', 'admin.toggle_admin', url_kwargs=dict(id='id'))


class ItemTableLocked(Table):
    name = Col('Panel')
    username = Col('Locked By')
    toggle_lock = LinkCol('Toggle Lock', 'admin.toggle_locked', url_kwargs=dict(id='id'))


admin = Blueprint('admin', __name__, template_folder='templates')


@admin.route('/user', methods=['GET', 'POST'])
@login_required
@admin_required
def user_admin():
    """
    view to allow users to be added and admin rights toggled

    :return: render html template
    """
    form = UserForm()
    message = None
    if request.method == 'POST':
        username = request.form["name"]
        if check_if_admin(s, current_user.id):
            create_user(s, username)
            message = "Added user: " + username
        else:
            return render_template('users.html', form=form, message="You can't do that")
    users = get_users(s)
    result = []
    for i in users:
        if i.username != current_user.id:
            row = dict(zip(i.keys(), i))
            result.append(row)
    table = ItemTableUsers(result, classes=['table', 'table-striped'])
    return render_template('users.html', form=form, table=table, message=message)


@admin.route('/user/toggle', methods=['GET', 'POST'])
@login_required
@admin_required
def toggle_admin():
    """
    toggles admin rights of a user

    :return: redirect to user_admin
    """
    user_id = request.args.get('id')
    toggle_admin_query(s, user_id)
    return redirect(url_for('admin.user_admin'))



@admin.route('/logs', methods=['GET', 'POST'])
@login_required
@admin_required
def view_logs():
    """
    view admin logs so that you can see what users have been doing

    :return: render hmtl template
    """
    if request.args.get('file'):
        log = request.args.get('file')
    else:
        log = 'PanelPal.log'

    import glob
    files = []
    listing = glob.glob('*log*')
    for filename in listing:
        files.append(filename)

    result = []
    with open(log) as f:
        for line in f:
            result.append(line.rstrip())

    return render_template('logs.html', log=result, files=files)


app/mod_admin/templates/locked.html
{% extends "layout.html" %}

{% block content %}

<h2>Locked Panels</h2>
<div class="row bttm-buffer">
    <div class="col-md-12">
        {% if message %}
        <div class="alert alert-success" id="message-fade"><strong>FYI</strong> {{ message }}</div>
        {% endif %}
    </div>
</div>
<div class="row bttm-buffer">
    <div class="col-md-12">
        {{ table }}
    </div>
</div>

{% endblock %}

app/mod_admin/templates/logs.html
{% extends "layout.html" %}

{% block content %}
<h2>Action Logs</h2>
<h3>Available Logs</h3>
<div class="row bttm-buffer">
    <div class="col-md-12">
        {% for i in files %}

        <a href="{{ url_for('admin.view_logs',file=i ) }}">{{ i }}</a><br>

        {% endfor %}
    </div>
</div>
<div class="row top-buffer bttm-buffer">
    <div class="col-md-12">
        <div class="pre-scrollable logs">


            {% for i in log %}

            {{ i }}<br>

            {% endfor %}

        </div>
    </div>
</div>


{% endblock %}

app/mod_admin/templates/permissions_admin.html
{% extends "layout.html" %}

{% block content %}

<div class="wrapper">
<form action="{{ url_for('admin.edit_permissions_admin') }}" method="POST" class="form-permissions">
    <h2>Edit User Permissions</h2><br>
    {% if message %}
<div class="alert alert-success" id="message-fade"><strong>FYI</strong> {{ message }}</div>
{% endif %}
    Tick boxes and click "Submit Changes" to give users permission to certain projects.<br><br>
    <table class="table table-striped">
        <thead>
        <th>
            User
        </th>
        <th>
            Projects
        </th>

        </thead>
        {% for username in permissions %}
        <tr>
            <td>
                {{ username }}
            </td>
            <td>
                <div class="form-group">
                    {% for project_id in permissions[username] %}


                    <label>{{ permissions[username][project_id]["name"] }} </label>

                    <input value="{{username}}_{{project_id}}" name="check" id="checkbox" type="checkbox" {{
                           permissions[username][project_id]['checked'] }}>

                    {% endfor %}
                </div>
            </td>


        </tr>

        {% endfor %}

    </table>
        <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Submit Changes">
    </div>


</form>
</div>
{% endblock %}

app/mod_admin/templates/users.html
{% extends "layout.html" %}
 
{% block content %}

<div class="wrapper">

  <form action="{{ url_for('admin.user_admin') }}" method="POST" class="form-create" >

    <h2>Add User</h2>


    {% for message in form.name.errors %}
  <div class="alert alert-danger">Oh Snap! {{ message }}</div>
{% endfor %}
     {% if message %}
<div class="alert alert-success" id="message-fade"><strong>FYI</strong> {{ message }}</div>
{% endif %}

    {{ form.hidden_tag() }}
    <div class="form-group">
    {{ form.name.label }}
    {{ form.name(class_="form-control") }}
    </div>
    {{ form.submit(class_="btn btn-primary") }}

      <h2>Users</h2>
<div class="white-bk">
{{ table }}
</div>
  </form>




</div>

 {% endblock %}