app/mod_summary/views.py
from collections import OrderedDict

from app.queries import get_users, get_username_by_user_id
from flask import Blueprint
from flask import render_template, request, url_for, redirect
from flask.ext.login import login_required, current_user

from app.performance_summary import s
from app.views import admin_required
from flask_table import Table, Col, LinkCol

from producers.StarLims import StarLimsApi
from producers.eqaAPI import EqaAPI


summary = Blueprint('summary', __name__, template_folder='templates')


@summary.route('/search', methods=['GET', 'POST'])
@login_required
@admin_required
def search():
    if request.method == 'POST':
        staff = request.form["staff"]
        if staff == "":
            return render_template('search.html', list=list, modifier="OOOoooops!",
                                   message="You Must Enter a Search Term!")
        s = StarLimsApi()
        all_staff = []
        samples_by_user = s.get_samples_by_user(staff)
        reports_by_user = s.get_report_samples_by_user(staff)
        if "FAIL" not in samples_by_user[0]:
            for i in samples_by_user:
                all_staff.append(i["FULLNAME"])
        if "FAIL" not in reports_by_user[0]:
            for i in reports_by_user:
                all_staff.append(i["FULLNAME"])

        unique_staff = set(all_staff)
        if len(unique_staff) > 0:
            return search_list(unique_staff)
        else:
            return render_template('search.html', list=list, modifier="Hey!", message="\"" + staff + "\" Not Found in Starlims! Try Another Search...")


@summary.route('/summary', methods=['GET', 'POST'])
@login_required
@admin_required
def staff_summary():
    staff_name = request.args["staff"]
    s = StarLimsApi()
    e = EqaAPI()
    all_samples = []
    starlims_samples = s.get_samples_by_user(staff_name)
    starlims_reports = s.get_report_samples_by_user(staff_name)
    for i in starlims_samples:
        all_samples.append(i["FOLDERNO"])
    for i in starlims_reports:
        all_samples.append(i["FOLDERNO"])
    unique_samples = set(all_samples)
    results=[]
    for sample in unique_samples:
        print sample
        eqa_result = e.get_scheme_by_snumber(sample)[0]
        if "FAIL" not in eqa_result:
            events = []
            for i in starlims_samples:
                if i["FOLDERNO"] == eqa_result["SampleStarlimsRef"]:
                    event = {}
                    event["STEP"] = i["STEPCODE"]
                    event["TYPE"] = i["EVENTTYPE"]
                    events.append(event)
            for i in starlims_reports:
                if i["FOLDERNO"] == eqa_result["SampleStarlimsRef"]:
                    event = {}
                    event["TYPE"] = i["EVENTCOMMENT"]
                    event["STEP"] = i["EVENTSTATUS"]
                    events.append(event)
            eqa_result["EVENTS"]=events
            results.append(eqa_result)

    result_count=len(results)
    sample_count=len(unique_samples)

    for result in results:
        print result
        if "ResultStatus" not in result:
            result["ResultStatus"] = "In Progress"

    return render_template('staff_record.html',name=staff_name,sample_count=sample_count,result_count = result_count,results = results)

@summary.route('/search/list', methods=['GET', 'POST'])
@login_required
@admin_required
def search_list(list=None):
    if list is not None:
        return render_template('staff_list.html',list=list)









app/mod_summary/templates/search.html
{% extends "layout.html" %}

{% block content %}
<div class="row top-buffer">
    <div class="col-md-12">
        <h1>Search</h1>
    </div>
</div>
{% if message %}
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-warning"><strong>{{ modifier }}</strong> {{ message }}</div>
    </div>
</div>
{% endif %}
<div class="row">
    <div class="col-md-12">
        <form action="{{  url_for('summary.search') }}" method="post" class="form" role="search">
            <div class="form-group">
                <input type="text" name="staff" class="form-control" placeholder="Staff Name">
            </div>
            <button type="submit" class="btn btn-default" onclick="loading()">Search</button>
        </form>
    </div>
</div>
{% endblock %}

app/mod_summary/templates/staff_list.html
{% extends "layout.html" %}

{% block content %}
<div class="row top-buffer">
    <div class="col-md-12">
<h3>The following staff match your search:</h3><br><br>
        </div>
    </div>
<div class="row bttm-buffer">
    <div class="col-md-12">
        <table class="table table-striped">
            <!--<thead>-->
            <!--<tr>-->
                <!--<th>Select Staff Member</th>-->
            <!--</tr>-->
            <!--</thead>-->
            {% for name in list %}
            <tr>
                <td><a href="{{ url_for('summary.staff_summary') }}?staff={{ name }}"  onclick="loading();">{{name}}</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock %}

app/mod_summary/templates/staff_record.html
{% extends "layout.html" %}

{% block content %}
<div class="row top-buffer">
    <div class="col-md-12">
        <h1>{{ name }}</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Competency Record
            </div>
            <div class="panel-body">
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                EQA Summary (Past 2 Years)
            </div>
            <div class="panel-body">
                <p>Participated in {{ sample_count }} EQA samples</p>

                <p>{{ result_count }} of these samples have data in the EQA database</p>
                {% if result_count > 0 %}
                <div id="accordion">
                    {% for result in results %}
                    <h3>{{ result["SampleStarlimsRef"] }} - {{ result["ResultStatus"] }}</h3>
                    <div>
                        <p><strong>Scheme Summary:</strong></p>
                        <table class="table table-bordered">
                            <tr>
                                <td><strong>Scheme</strong></td>
                                <td>{{ result["SchemeName"] }}</td>
                            </tr>
                            <tr>
                                <td><strong>Submission Date</strong></td>
                                <td>{{ result["SubmissionDate"] }}</td>
                            </tr>
                            <tr>
                                <td><strong>Result Score</strong></td>
                                <td>{{ result["ResultScore"] }}</td>
                            </tr>
                            <tr>
                                <td><strong>Result Comments</strong></td>
                                <td>{{ result["Scheme_Comment"] }}</td>
                            </tr>
                        </table>
                        <p><strong>The following steps were completed by this individual in StarLims:</strong></p>
                        <table class="table table-bordered">
                            {% for event in result["EVENTS"] %}
                            <tr>
                                <td>{{ event["TYPE"] }}</td>
                                <td>{{ event["STEP"] }}</td>
                            </tr>

                            {% endfor %}

                        </table>

                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Incidents
            </div>
            <div class="panel-body">
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $("#accordion").accordion({
            collapsible: true,
            active: false
        });
    });
</script>

{% endblock %}